### ISSUE TITLE
Rulebook priorities

### ISSUE THREAD

**Issue by clayote** [TacticalMetaphysics/LiSE#57]
Currently, if you want to change the order your rulebooks are executed in, you can't really; you have to change the name of the entity the rulebook's on. You ought to be able to change a priority number to get a different ordering.

That change ought to be journaled, if only because the order of the rules within the rulebook already is.

**Comment by LogicalDash** [comment]
In efbf0bd4ccd02e0a0ae47ffc809b7a33b6e866ad, I changed the poller to follow rulebooks in order of *their* name, which defaults to the name of the entity but can be set arbitrarily. You could use this to approximate priorities, and it will make it easier to actually implement priorities in the future.
