### ISSUE TITLE
Urizen map import

### ISSUE THREAD

**Issue by clayote** [TacticalMetaphysics/LiSE#78]
[Urizen](https://github.com/vurmux/urizen) is a tool for generating maps for roguelikes and whatnot. A user who's made a cool map with it should be able to use that map as the initial state for a LiSE simulation.

**Comment by LogicalDash** [comment]
Since Urizen's tileset is so much more expansive than the RLTiles, it might be a good idea to switch to that, as well...

**Comment by clayote** [comment]
Urizen is unmaintained three years hence. Closing this issue.

I think there are some other map generators floating around itch.io I'd like to support...but I'll wait and see which result in the most maps actually getting made with them.
